"""keyval

Revision ID: 2ddd492e5d41
Revises: 5aa86fe8ae93
Create Date: 2016-04-15 18:46:07.645750

"""

# revision identifiers, used by Alembic.
revision = '2ddd492e5d41'
down_revision = '5aa86fe8ae93'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyval')
    ### end Alembic commands ###
