"""initial tables

Revision ID: 5aa86fe8ae93
Revises: 
Create Date: 2016-04-15 18:35:47.827217

"""

# revision identifiers, used by Alembic.
revision = '5aa86fe8ae93'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fb_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fb_id', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fb_alert')
    ### end Alembic commands ###
